package FX;

import javafx.fxml.FXML;
import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.Cursor;
import javafx.scene.Node;
import javafx.scene.control.Button;

import javafx.scene.layout.HBox;

import java.util.List;
import java.util.Set;

import org.controlsfx.control.Notifications;

import buisness.popupBuisness;
import entities.Message;
import entities.MessageReport;
import entities.Notification;
import entities.Reply;
import entities.ReplyReport;
import javafx.event.ActionEvent;
import javafx.event.Event;
import javafx.event.EventHandler;
import javafx.scene.control.ScrollPane;
import javafx.scene.control.Separator;
import javafx.scene.control.TextArea;
import javafx.scene.image.ImageView;
import javafx.scene.control.CheckBox;
import javafx.scene.control.Label;
import javafx.scene.layout.VBox;
import javafx.scene.text.Font;
import javafx.stage.Stage;
import javafx.util.Duration;

public class popuprelpyController {
	@FXML
	private VBox vboxkol;
	@FXML
	private TextArea Replyr;
	@FXML
	private HBox hboxreportedby;
	@FXML
	private ScrollPane reportedby;
	@FXML
	private VBox reports;
	@FXML
	private VBox vboxcheckbox;
	@FXML
	private CheckBox notify;
	@FXML
	private CheckBox replydelete;
	@FXML
	private CheckBox discudelete;
	@FXML
	private CheckBox acountdelete;
	@FXML
	private CheckBox msgdelete;
	@FXML
	private Button apply;

	public static Reply r;
	private Reply r1;

	private popupBuisness p;

	@FXML
	public void initialize() {

		p = new popupBuisness();

		r1 = r;
		Replyr.setText(r1.getText());
		Replyr.setEditable(false);
		System.out.println("eeeeeeeeeeeeeee" + r1.getReportes());

		for (ReplyReport mr : r1.getReportes()) {
			HBox h = new HBox();
			Label l = new Label("username :" + mr.getReporter().getUserName() + ", reason:");
			l.setCursor(Cursor.HAND);
			l.setPadding(new Insets(10, 20, 0, 30));
			l.setFont(Font.font("Bold", 16));
			l.setOnMouseClicked(new EventHandler<Event>() {
				@Override
				public void handle(Event event) {
					 new Profile().showProfile(mr.getReporter());
				}

			});

			h.getChildren().add(new ImageView("images/profile.png"));
			h.getChildren().add(l);
			TextArea txt = new TextArea(mr.getReason());
			txt.setEditable(false);
			txt.setMaxHeight(40);
			h.getChildren().add(txt);

			Separator sep = new Separator();
			sep.setPadding(new Insets(10, 0, 10, 0));
			reports.getChildren().add(h);
			reports.getChildren().add(sep);
		}

	}

	// Event Listener on Button.onAction
	@FXML
	public void decline(ActionEvent event) {
		// TODO Autogenerated
		Set<ReplyReport> lcr = r1.getReportes();
		for (ReplyReport rr : lcr) {
			rr.setTreated(true);
			p.declineReplyRepored(rr);
		}

		
		Stage stage = (Stage) ((Node) event.getSource()).getScene().getWindow();

		stage.close();
		Notifications nb = Notifications.create().darkStyle().hideAfter(Duration.seconds(5)).title("Update")
				.text("Reply has been treated!").graphic(vboxkol).position(Pos.CENTER).hideCloseButton()
				.onAction(new EventHandler<ActionEvent>() {
					@Override
					public void handle(ActionEvent event) {
						//MainApp.s.close();
					}
				});
		nb.showConfirm();
	}

	// Event Listener on Button[#apply].onAction
	@FXML
	public void validate(ActionEvent event) {
		// TODO Autogenerated

		Stage stage = (Stage) ((Node) event.getSource()).getScene().getWindow();
		stage.close();
		
		if (notify.isSelected()) {

			Notification n = new Notification();
			n.setUser(r1.getOwner());
			n.setText("Your Reply:'" + r1.getText() + "' has been reported ");
			n.setType("rep" + r1.getMessage().getMessageID());

			p.addnotify(n);

		}
		
		if (acountdelete.isSelected()) {
			p.blockacount(r1.getOwner());
			Notifications nb = Notifications.create().darkStyle().hideAfter(Duration.seconds(5)).title("Update")
					.text("Acount  blocked !").graphic(vboxkol).position(Pos.CENTER).hideCloseButton()
					.onAction(new EventHandler<ActionEvent>() {
						@Override
						public void handle(ActionEvent event) {
							//MainApp.s.close();
						}
					});
			nb.showConfirm(); 
		}
		
		if (discudelete.isSelected()) {
			p.deleteMsg(r1.getMessage());Notifications nb = Notifications.create().darkStyle().hideAfter(Duration.seconds(5)).title("Update")
					.text("Message has been delted").graphic(vboxkol).position(Pos.CENTER).hideCloseButton()
					.onAction(new EventHandler<ActionEvent>() {
						@Override
						public void handle(ActionEvent event) {
							//MainApp.s.close();
						}
					});
			nb.showConfirm(); 
			
			
			return ; 
		}
		if (replydelete.isSelected()) {
			p.deleteReplies(r1);
			
			Notifications nb = Notifications.create().darkStyle().hideAfter(Duration.seconds(5)).title("Update")
					.text("Reply has been deleted!").graphic(vboxkol).position(Pos.CENTER).hideCloseButton()
					.onAction(new EventHandler<ActionEvent>() {
						@Override
						public void handle(ActionEvent event) {
							//MainApp.s.close();
						}
					});
			nb.showConfirm(); 
			return ; 
		}
		
		
		Set<ReplyReport> lcr = r1.getReportes();
		for (ReplyReport rr : lcr) {
			rr.setTreated(true);
			p.declineReplyRepored(rr);
		}
		
		

	}
}
