package FX;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;

import java.io.IOException;

import javax.naming.NamingException;
import javax.security.auth.Subject;

import buisness.DiscussionReportsBuisness;
import entities.Discussion;
import entities.DiscussionReport;
import javafx.event.ActionEvent;

import javafx.scene.control.TitledPane;
import javafx.scene.Scene;
import javafx.scene.control.TextArea;
import javafx.scene.layout.AnchorPane;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

public class ReportedDiscussionController {
	@FXML
	private TitledPane reportNumber;
	@FXML
	private VBox reporters;
	@FXML
	private TextArea subject;
	@FXML
	private Discussion dis;
	@FXML
	private DiscussionReport disR;

	public static Discussion d;

	public static DiscussionReport dr;

	@FXML
	public void initialize() {
		this.dis = d;
		this.disR = dr;
		reportNumber.setText("Report :");
		subject.setText(d.getTopic());
		for (DiscussionReport dr : dis.getReports()) {
			this.dr = dr;
			try {
				reporters.getChildren().add((AnchorPane) FXMLLoader.load(getClass().getResource("UserReport.fxml")));
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
	}

	// Event Listener on Button.onAction
	@FXML
	public void declinereport(ActionEvent event) throws NamingException {
		disR.setTreated(true);
		new DiscussionReportsBuisness().declineDiscussionReported(disR);
	}

	// Event Listener on Button.onAction
	@FXML
	public void deleteDiscussion(ActionEvent event) throws NamingException {
		new DiscussionReportsBuisness().deleteDiscussion(dis);
	}
	// Event Listener on Button.onAction

	@FXML
	public void viewDiscussion(ActionEvent event) {
		Stage primaryStage = new Stage();
		AnchorPane root;

		try {
			ViewDiscussionReportedController.d=this.dis;
			root = (AnchorPane) FXMLLoader.load(getClass().getResource("ViewDiscussionReported.fxml"));
			Scene scene = new Scene(root);
			primaryStage.setScene(scene);
			primaryStage.show();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}

	// Event Listener on Button.onAction
	@FXML
	public void viewOwner(ActionEvent event) {
		// TODO Autogenerated
	}
}
